endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

zuul:
  routes:
    workspaces:
      path: /workspaces-service/**
      serviceId: workspaces-api
    employees:
      path: /employees-service/**
      serviceId: employees-api
